---
apiVersion: v1
kind: Service
metadata:
  name: whatsmyip
  labels:
    name: whatsmyip
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: whatsmyip
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: whatsmyip
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: whatsmyip
    spec:
      containers:
      - name: nginx
        image: apareek/nginx:v1.1
        ports:
          - containerPort: 80
            name: nginx-port
      - name: flask-what-is-my-ip-app
        image: apareek/flask-what-is-my-ip-app:v1.1
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
